export const CREATE_ADMIN_ASYNC = 'CREATE_ADMIN_ASYNC';
export const CREATE_ADMIN_SUCCESS = 'CREATE_ADMIN_SUCCESS';
export const CREATE_ADMIN_FAILD = 'CREATE_ADMIN_FAILD';
export const ADMIN_RESET = 'ADMIN_RESET';