export const GET_USER_LIST_ASYNC = 'GET_USER_LIST_ASYNC';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILD = 'GET_USER_LIST_FAILD';
export const REMOVE_USER = 'REMOVE_USER';